<?php
require_once __DIR__ . '/../includes/bootstrap.php';
$activeNav='expenses'; $pageTitle='Expenses'; $pageAction='<button class="btn-primary px-4 py-2 rounded label uppercase" data-open-template-modal="expense-add-template" data-modal-title="Add Expense" data-modal-icon="payments" data-modal-subtitle="Record operating costs for profit and cash-flow reports."><span class="material-symbols-outlined text-base align-middle">add</span> Add Expense</button>'; require_permission('expenses.manage');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['csrf_token']??null);db()->prepare('INSERT INTO expenses (category,amount,expense_date,description,user_id) VALUES (?,?,?,?,?)')->execute([$_POST['category'],(float)$_POST['amount'],$_POST['expense_date'],trim($_POST['description']),current_user()['id']]);audit_log('CREATE_EXPENSE','expenses',(int)db()->lastInsertId());header('Location: '.ADMIN_BASE.'/expenses.php?toast=Expense created successfully.');exit;}
$rows=db()->query('SELECT e.*, u.name user_name FROM expenses e LEFT JOIN users u ON u.id=e.user_id ORDER BY e.expense_date DESC,e.id DESC')->fetchAll();
require __DIR__ . '/../includes/admin_header.php';
?>
<template id="expense-add-template"><form method="post" class="space-y-3"><?= csrf_field() ?><select class="input" name="category"><?php foreach(['Rent','Internet','Electricity','Maintenance','Salaries','Supplies','Other'] as $c): ?><option><?= e($c) ?></option><?php endforeach; ?></select><input class="input" name="amount" type="number" step="0.01" placeholder="Amount" required><input class="input" name="expense_date" type="date" value="<?= date('Y-m-d') ?>"><input class="input" name="description" placeholder="Description"><div class="modal-foot -mx-4 -mb-4 mt-4"><button type="button" class="btn-secondary" data-close-modal>Cancel</button><button class="btn-primary rounded label uppercase">Add Expense</button></div></form></template>
<section class="panel overflow-auto"><table class="table"><thead><tr><th>Date</th><th>Category</th><th>Amount</th><th>Description</th><th>User</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['expense_date']) ?></td><td><?= e($r['category']) ?></td><td><?= money($r['amount']) ?></td><td><?= e($r['description']) ?></td><td><?= e($r['user_name']) ?></td></tr><?php endforeach; ?></tbody></table></section>
<?php require __DIR__ . '/../includes/admin_footer.php'; ?>
