<?php
require_once __DIR__ . '/../includes/bootstrap.php';
$activeNav='reservations'; $pageTitle='Reservations'; $pageAction='<button class="btn-primary px-4 py-2 rounded label uppercase" data-open-template-modal="reservation-add-template" data-modal-title="Create Reservation" data-modal-icon="calendar_month" data-modal-subtitle="Book a station time slot and prevent double booking."><span class="material-symbols-outlined text-base align-middle">add</span> Add Reservation</button>'; require_permission('sessions.manage');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['csrf_token']??null);$kind=$_POST['station_kind']==='PLAYSTATION'?'PLAYSTATION':'PC';$station=(int)$_POST['station_id'];$date=$_POST['reservation_date'];$time=$_POST['start_time'];$duration=max(15,(int)$_POST['duration_minutes']);$end=date('H:i:s',strtotime($time)+$duration*60);$col=$kind==='PC'?'station_id':'playstation_station_id';$stmt=db()->prepare("SELECT COUNT(*) FROM reservations WHERE station_kind=? AND $col=? AND reservation_date=? AND status IN ('UPCOMING','ACTIVE') AND start_time < ? AND ADDTIME(start_time, SEC_TO_TIME(duration_minutes*60)) > ?");$stmt->execute([$kind,$station,$date,$end,$time]);if($stmt->fetchColumn()>0){$error='Double booking rejected for this station/time.';}else{$walkInId=walk_in_customer_id();db()->prepare("INSERT INTO reservations (customer_id, station_kind, $col, reservation_date, start_time, duration_minutes, created_by) VALUES (?,?,?,?,?,?,?)")->execute([$walkInId,$kind,$station,$date,$time,$duration,current_user()['id']]);header('Location: '.ADMIN_BASE.'/reservations.php?toast=Reservation created successfully.');exit;}}
$pcs=db()->query('SELECT id,name FROM stations ORDER BY name')->fetchAll();$ps=db()->query('SELECT id,name FROM playstation_stations ORDER BY name')->fetchAll();$rows=db()->query('SELECT r.*, s.name pc, p.name ps FROM reservations r LEFT JOIN stations s ON s.id=r.station_id LEFT JOIN playstation_stations p ON p.id=r.playstation_station_id ORDER BY r.reservation_date DESC,r.start_time DESC')->fetchAll();
require __DIR__ . '/../includes/admin_header.php';
?>
<?php if(!empty($error)): ?><div class="panel p-3 mb-4 text-status-busy"><?= e($error) ?></div><?php endif; ?>
<template id="reservation-add-template"><form method="post" class="space-y-3"><?= csrf_field() ?><select class="input" name="station_kind"><option>PC</option><option>PLAYSTATION</option></select><select class="input" name="station_id"><?php foreach($pcs as $s): ?><option value="<?= $s['id'] ?>"><?= e($s['name']) ?></option><?php endforeach; ?><?php foreach($ps as $s): ?><option value="<?= $s['id'] ?>"><?= e($s['name']) ?></option><?php endforeach; ?></select><input class="input" type="date" name="reservation_date" value="<?= date('Y-m-d') ?>"><input class="input" type="time" name="start_time" required><input class="input" type="number" name="duration_minutes" value="60"><div class="modal-foot -mx-4 -mb-4 mt-4"><button type="button" class="btn-secondary" data-close-modal>Cancel</button><button class="btn-primary rounded label uppercase">Reserve</button></div></form></template>
<section class="panel overflow-auto"><table class="table"><thead><tr><th>Station</th><th>Date</th><th>Start</th><th>Duration</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td class="text-white"><?= e($r['pc'] ?: $r['ps']) ?></td><td><?= e($r['reservation_date']) ?></td><td><?= e($r['start_time']) ?></td><td><?= e($r['duration_minutes']) ?>m</td><td><?= e($r['status']) ?></td></tr><?php endforeach; ?></tbody></table></section>
<?php require __DIR__ . '/../includes/admin_footer.php'; ?>
